### ISSUE TITLE
Carpeta de Py duplicada

### ISSUE THREAD

**Issue by Luicha** [CodeSystem2022/Uritorco_UTN_Tercer_Semestre_2023#1]
Tenemos dos veces la carpeta con los ejercicios de Python: 

> - > Python/Tecnicatura3py, y
> - > Tecnicatura3py

Borramos la segunda o vemos si hay algo que podamos llevar de una a otra? 🤔

**Comment by 1984hats** [comment]
Tecnicatura3py, tendríamos que borrarla, pero lo vemos en el grupo por privado. Sugiero hacer un meet para coordinar bien todo

**Comment by Vera2376** [comment]
Chicos esta carpeta abría que eliminarla para no crear confusión.

**Comment by 1984hats** [comment]
Solucionado lo de la carpeta duplicada
