### ISSUE TITLE
Posgrestsql Base de datos

### ISSUE THREAD

**Issue by Vera2376** [CodeSystem2022/Uritorco_UTN_Tercer_Semestre_2023#26]
Python y Postgresql enlazar la base de datos y hacer que funcione.
Cargarlo funcionando.

**Comment by 1984hats** [comment]
No me funciona el pip install en PyCharm en Windows11

**Comment by Vera2376** [comment]
Logrado y terminado se ejecuta python y pycharm desde otra terminal con Win 10.
